version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/project/forduellee_server
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: scripts/remove.sh
      timeout: 60
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60